- apiVersion: v1
  kind: profile
  metadata:
    name: backupctl
    tags:
    - backupctl
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: console
    tags:
    - console
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: lain
    tags:
    - lain
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: lvault
    tags:
    - lvault
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: registry
    tags:
    - registry
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
- apiVersion: v1
  kind: profile
  metadata:
    name: tinydns
    tags:
    - tinydns
  spec:
    egress:
    - action: allow
      destination: {}
      source: {}
    ingress:
    - action: allow
      destination: {}
      source: {}
