- name: config webrouter
  template: src=webrouter.service.j2 dest=/etc/systemd/system/webrouter.service
  notify:
    - reload systemd for webrouter
    - restart webrouter
- meta: flush_handlers

- name: ensure webrouter started
  service: name=webrouter enabled=yes state=started

- name: checking webrouter working correctly
  shell: "docker ps | grep webrouter.service"
  register: result
  until: result|success
  retries: 50
  delay: 5
  changed_when: False
